<a href="https://colab.research.google.com/github/Jack21Ace/Fundamentos-de-Programacion/blob/master/algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
escalar = 3
vector = np.array([1, 2, 3])
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

suma = matriz + matriz
producto_escalar = escalar * matriz 
print(producto_escalar)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
